version: '3.7'

services:
  django_backend:
    volumes:
      - static:/static
    env_file:
      - .env
    build: 
      context: .
    ports:
      - "8000:8000"

  nginx-server:
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - "80:80"
    depends_on:
      - django_backend
volumes:
  static:
